eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9088
spring:
  application:
    name: "manage"
  datasource:
    url: jdbc:mysql://192.168.138.101:3306/cas?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  redis:
    database: 0
    host: 192.168.138.101
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/myProject/dao/mapper/*.xml
