eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9088
spring:
  application:
    name: "manage"
  datasource:
    url: jdbc:mysql://10.60.0.54:3306/labsys1?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
mybatis:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/myProject/dao/mapper/*.xml
