server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
